In [3]:
import numpy as np
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

# 배열 뒤집기
w_r = np.flip(w)
w_r

array([3, 5, 1, 2])

In [6]:
#합성곱 계산
for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [7]:
#사이파이에서 제공하는 합성곱 함수 - w를 뒤집어서 곱하는 방식
from scipy.signal import convolve
convolve(x, w, mode='valid') # valid: 원본 배열에 패딩을 추가하지 않음

array([63, 48, 49, 28, 21, 20])

In [8]:
#교차상관방식 - w를 뒤집지 않고 곱하는 방식
from scipy.signal import correlate
correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

In [9]:
#full패딩 - 원본 배열의 모든 원소가 연산에 동일하게 참여
correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [11]:
#same패딩 - 출력 배열의 길이가 원본 배열의 길이와 같아지도록 제로패딩을 추가
correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [12]:
#2차원 배열에 대한 합성곱 계산
from scipy.signal import correlate2d
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
w = np.array([[2, 0], 
              [0, 0]])
correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [13]:
#same패딩
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
w = np.array([[2, 0], 
              [0, 0]])
correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
#텐서플로에서 지원하는 합성곱 함수 
import tensorflow as tf
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
with tf.device('/CPU:0'):
    # 입력값: reshape(batch, height, width, channel) - 4차원 배열
    x_4d = x.astype(np.float).reshape(1, 3, 3, 1) # 실수형으로 입력
    # 필터(가중치): reshape(height, width, channel, 가중치의 개수)
    w_4d = w.reshape(2, 2, 1, 1)
    # SAME 대문자로 작성
    c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')
    # 텐서를 넘파이 배열로 변환
    print(c_out.numpy().reshape(3, 3))

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


C:\Users\tjoeun\AppData\Local\Temp\ipykernel_11884\1027495732.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x_4d = x.astype(np.float).reshape(1, 3, 3, 1) # 실수형으로 입력


In [15]:
#맥스풀링
# 입력값: reshape(샘플수, height, width, channel)
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8], 
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])
x = x.reshape(1, 4, 4, 1)
# ksize: 커널사이즈, strides: 이동간격
with tf.device('/CPU:0'):
    p_out = tf.nn.max_pool2d(x, ksize=2, strides=2, padding='SAME')
    print(p_out.numpy().reshape(2, 2))

[[ 6.  8.]
 [14. 16.]]
