In [1]:
#gpu 사용 가능 여부
import torch
print(torch.cuda.is_available())

True


In [3]:
#gpu 장치의 인덱스
torch.cuda.current_device()

0

In [4]:
#사용가능한 gpu장치수
torch.cuda.device_count()

1

In [5]:
#gpu 이름
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1050 Ti'

In [6]:
#텐서 자료를 gpu에 저장
cuda = torch.device('cuda')
a = torch.tensor([1, 2], device=cuda)
b = torch.tensor([1, 2]).cuda()
c = torch.tensor([1, 2]).to(device=cuda)
print(a)
print(b)
print(c)

tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')


In [7]:
#사용하지 않는 텐서 정리
torch.cuda.empty_cache()